"""create relationship between users and tasks table

Revision ID: 50d8d217f120
Revises: cdc618c37419
Create Date: 2024-09-09 16:45:56.123293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50d8d217f120'
down_revision: Union[str, None] = 'cdc618c37419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_tasks_user_id',  # Nome da constraint
            'users',             # Tabela de referência
            ['user_id'],         # Colunas na tabela atual
            ['id'],              # Colunas na tabela de referência
            ondelete='CASCADE'  # Opção adicional
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_user_id', type_='foreignkey')  # Nome da constraint
        batch_op.drop_column('user_id')  # Apenas o nome da coluna
    # ### end Alembic commands ###
