"""fix model imports

Revision ID: bfc65e5d60b7
Revises: 50d8d217f120
Create Date: 2024-09-09 17:14:30.193528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'bfc65e5d60b7'
down_revision: Union[str, None] = '50d8d217f120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Remove the old constraint with a name
        batch_op.drop_constraint('fk_tasks_user_id', type_='foreignkey')
        # Add the new foreign key constraint
        batch_op.create_foreign_key(
            'fk_tasks_user_id',  # Nome da constraint
            'users',  # Tabela referenciada
            ['user_id'],  # Coluna na tabela atual
            ['id']  # Coluna na tabela referenciada
        )
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        # Remove the new constraint with a name
        batch_op.drop_constraint('fk_tasks_user_id', type_='foreignkey')
        # Recria a constraint original
        batch_op.create_foreign_key(
            'fk_tasks_user_id',  # Nome da constraint
            'users',  # Tabela referenciada
            ['user_id'],  # Coluna na tabela atual
            ['id'],  # Coluna na tabela referenciada
            ondelete='CASCADE'  # Opção de exclusão em cascata
        )
    # ### end Alembic commands ###
