"""fix model imports and relationships

Revision ID: cee7d66c1140
Revises: bfc65e5d60b7
Create Date: 2024-09-09 17:24:22.795642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cee7d66c1140'
down_revision: Union[str, None] = 'bfc65e5d60b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
